Repository bitbit-Merry-go-round/Transcendence-BE, pull requests merged in 2024-04, with the labels that each got.

#41 fix(#39): 프론트와 로그인 연결 문제 해결
  srcs/backend/srcs/add_provider.py
  srcs/backend/srcs/backend/settings.py
  srcs/backend/srcs/fourtytwo/__init__.py
  srcs/backend/srcs/fourtytwo/apps.py
  srcs/backend/srcs/fourtytwo/migrations/__init__.py
  srcs/backend/srcs/fourtytwo/provider.py
  srcs/backend/srcs/fourtytwo/urls.py
  srcs/backend/srcs/fourtytwo/views.py
  srcs/backend/srcs/users/adapter.py
  srcs/backend/srcs/users/models.py
  srcs/backend/srcs/users/urls.py
  srcs/backend/srcs/users/views.py
  srcs/backend/tools/requirements.txt
  srcs/backend/tools/run_backend.sh
Labels: 🐛 Bug

#45 feat(#44): JWT 발급 기능 추가
  srcs/backend/srcs/add_user.py
  srcs/backend/srcs/backend/settings.py
  srcs/backend/srcs/users/models.py
  srcs/backend/srcs/users/serializers.py
  srcs/backend/srcs/users/urls.py
  srcs/backend/srcs/users/views.py
  srcs/backend/tools/run_backend.sh
Labels: ✨ Feature, ♻️ Refactor

#49 feat(#14): 2FA
  srcs/backend/srcs/.env
  srcs/backend/srcs/backend/settings.py
  srcs/backend/srcs/users/models.py
  srcs/backend/srcs/users/urls.py
  srcs/backend/srcs/users/utils.py
  srcs/backend/srcs/users/views.py
Labels: ✨ Feature

#54 feat(#50): 로그아웃 기능 구현
  srcs/.env
  srcs/backend/srcs/backend/settings.py
  srcs/backend/srcs/backend/urls.py
  srcs/backend/srcs/backend/views.py
  srcs/backend/srcs/users/models.py
  srcs/backend/srcs/users/utils.py
  srcs/backend/srcs/users/views.py
  srcs/compose.yaml
  srcs/user-manager/srcs/users/models.py
  srcs/user-manager/srcs/users/serializers.py
  srcs/user-manager/srcs/users/tests.py
  srcs/user-manager/srcs/users/views.py
Labels: ✨ Feature

#57 fix(#46): 사용자 입력 오류 핸들링
  db_init.sh
  srcs/backend/srcs/add_user.py
  srcs/backend/srcs/backend/urls.py
  srcs/backend/srcs/backend/views.py
  srcs/backend/srcs/users/models.py
  srcs/backend/srcs/users/tests.py
  srcs/backend/srcs/users/urls.py
  srcs/backend/srcs/users/views.py
  srcs/user-manager/srcs/users/serializers.py
  srcs/user-manager/srcs/users/views.py
Labels: 🐛 Bug

#62 feat(#56): 전적 관련 기능 구현
  Makefile
  srcs/.env
  srcs/backend/srcs/backend/urls.py
  srcs/backend/srcs/game/__init__.py
  srcs/backend/srcs/game/apps.py
  srcs/backend/srcs/game/migrations/__init__.py
  srcs/backend/srcs/game/urls.py
  srcs/backend/srcs/game/views.py
  srcs/backend/srcs/users/views.py
  srcs/compose.yaml
  srcs/game/Dockerfile
  srcs/game/srcs/add_game.py
  srcs/game/srcs/game/__init__.py
  srcs/game/srcs/game/asgi.py
  srcs/game/srcs/game/settings.py
  srcs/game/srcs/game/urls.py
  srcs/game/srcs/game/wsgi.py
  srcs/game/srcs/manage.py
  srcs/game/srcs/records/__init__.py
  srcs/game/srcs/records/admin.py
  srcs/game/srcs/records/apps.py
  srcs/game/srcs/records/migrations/__init__.py
  srcs/game/srcs/records/models.py
  srcs/game/srcs/records/serializers.py
  srcs/game/srcs/records/urls.py
  srcs/game/srcs/records/views.py
  srcs/game/tools/requirements.txt
  srcs/game/tools/run_game.sh
Labels: ✨ Feature

#64 fix(#61): 유효하지 않은 경로 처리
  srcs/backend/srcs/backend/settings.py
  srcs/backend/srcs/game/views.py
  srcs/backend/srcs/users/views.py
  srcs/game/srcs/game/settings.py
  srcs/game/srcs/records/serializers.py
  srcs/game/srcs/records/urls.py
  srcs/game/srcs/records/views.py
  srcs/user-manager/srcs/user-manager/settings.py
  srcs/user-manager/srcs/users/serializers.py
  srcs/user-manager/srcs/users/urls.py
  srcs/user-manager/srcs/users/views.py
Labels: 🐛 Bug

#65 feat(#59): 사용자 프로필 업데이트
  srcs/backend/srcs/backend/views.py
  srcs/backend/srcs/game/views.py
  srcs/user-manager/srcs/users/models.py
  srcs/user-manager/srcs/users/serializers.py
  srcs/user-manager/srcs/users/views.py
Labels: ✨ Feature

#66 fix(#59): 1v1 게임에서만 사용자 프로필 업데이트
  srcs/backend/srcs/game/views.py
Labels: 🐛 Bug

#68 refactor: set sslserver (#18)
  srcs/backend/Dockerfile
  srcs/backend/srcs/backend/settings.py
  srcs/backend/srcs/backend/views.py
  srcs/backend/srcs/game/views.py
  srcs/backend/srcs/users/views.py
  srcs/backend/tools/requirements.txt
  srcs/backend/tools/run_backend.sh
  srcs/game/Dockerfile
  srcs/game/srcs/game/settings.py
  srcs/game/tools/requirements.txt
  srcs/game/tools/run_game.sh
  srcs/user-manager/Dockerfile
  srcs/user-manager/srcs/user-manager/settings.py
  srcs/user-manager/tools/requirements.txt
  srcs/user-manager/tools/run_user_manager.sh
Labels: ✨ Feature, ♻️ Refactor

#69 feat(#18): 다른 컨테이너에도 ssl 적용
  srcs/backend/Dockerfile
  srcs/backend/srcs/backend/settings.py
  srcs/backend/srcs/game/views.py
  srcs/backend/srcs/users/views.py
  srcs/backend/tools/run_backend.sh
  srcs/game/Dockerfile
  srcs/game/srcs/game/settings.py
  srcs/game/srcs/records/views.py
  srcs/game/tools/run_game.sh
  srcs/user-manager/Dockerfile
  srcs/user-manager/srcs/users/models.py
  srcs/user-manager/tools/run_user_manager.sh
Labels: ✨ Feature, ♻️ Refactor

#71 chore(#70): 더미 데이터 삭제
  srcs/game/srcs/add_game.py
  srcs/game/tools/run_game.sh
  srcs/user-manager/srcs/add_user.py
  srcs/user-manager/tools/run_user_manager.sh
Labels: ⚙️ Chore
