Repository bitbit-Merry-go-round/Transcendence-BE, pull requests merged in 2024-03, with the labels that each got.

#2 feat(#1): 프로젝트 초기 세팅
  mypong/db.sqlite3
  mypong/manage.py
  mypong/mypong/__init__.py
  mypong/mypong/asgi.py
  mypong/mypong/settings.py
  mypong/mypong/urls.py
  mypong/mypong/wsgi.py
  mypong/users/__init__.py
  mypong/users/admin.py
  mypong/users/apps.py
  mypong/users/migrations/__init__.py
  mypong/users/models.py
  mypong/users/tests.py
  mypong/users/urls.py
  mypong/users/views.py
Labels: ✨ Feature

#5 feat(#3): 장고에 DB 연결
  mypong/.env
  mypong/manage.py
  mypong/mypong/settings.py
  mypong/users/models.py
  mypong/users/serializers.py
  mypong/users/urls.py
  mypong/users/views.py
Labels: ✨ Feature

#8 feat(#6): 프로필 관련 기능 구현
  mypong/mypong/settings.py
  mypong/static/avatar.jpg
  mypong/users/models.py
  mypong/users/serializers.py
  mypong/users/urls.py
  mypong/users/views.py
Labels: ✨ Feature

#9 feat(#7): 친구 관련 기능 구현
  mypong/users/models.py
  mypong/users/serializers.py
  mypong/users/urls.py
  mypong/users/views.py
Labels: ✨ Feature

#10 docs(#4): Docker에 연동하기
  Makefile
  mypong/.env
  srcs/.env
  srcs/compose.yaml
  srcs/mypong/Dockerfile
  srcs/mypong/srcs/.env
  srcs/mypong/srcs/db.sqlite3
  srcs/mypong/srcs/manage.py
  srcs/mypong/srcs/mypong/__init__.py
  srcs/mypong/srcs/mypong/asgi.py
  srcs/mypong/srcs/mypong/settings.py
  srcs/mypong/srcs/mypong/urls.py
  srcs/mypong/srcs/mypong/wsgi.py
  srcs/mypong/srcs/static/avatar.jpg
  srcs/mypong/srcs/users/__init__.py
  srcs/mypong/srcs/users/admin.py
  srcs/mypong/srcs/users/apps.py
  srcs/mypong/srcs/users/migrations/__init__.py
  srcs/mypong/srcs/users/models.py
  srcs/mypong/srcs/users/serializers.py
  srcs/mypong/srcs/users/tests.py
  srcs/mypong/srcs/users/urls.py
  srcs/mypong/srcs/users/views.py
  srcs/mypong/tools/requirements.txt
  srcs/mypong/tools/run_mypong.sh
Labels: 📝 Docs, ✨ Feature

#16 feat(#6): 프로필에 필드 추가
  srcs/backend/srcs/users/models.py
  srcs/backend/srcs/users/serializers.py
  srcs/backend/srcs/users/views.py
Labels: ✨ Feature

#17 feat(#15): CORS 정책 설정
  srcs/backend/srcs/backend/settings.py
  srcs/backend/tools/requirements.txt
Labels: ✨ Feature

#25 chore(#20): Dummy data init script
  Makefile
  db_init.sh
Labels: ⚙️ Chore

#30 fix(#29): 토큰 인증 관련 오류 해결
  srcs/backend/srcs/backend/settings.py
  srcs/backend/srcs/users/views.py
Labels: 🐛 Bug

#32 feat(#22): 유저 검색 기능 추가
  srcs/backend/srcs/users/urls.py
  srcs/backend/srcs/users/views.py
Labels: ✨ Feature

#34 feat(#23): 친구인지 식별하는 필드 추가
  srcs/backend/srcs/add_provider.py
  srcs/backend/srcs/users/admin.py
  srcs/backend/srcs/users/serializers.py
  srcs/backend/srcs/users/views.py
Labels: ✨ Feature

#36 fix(#35): OAuth 관련 오류 해결
  srcs/backend/srcs/.env
  srcs/backend/srcs/backend/settings.py
  srcs/backend/srcs/fourtytwo/provider.py
  srcs/backend/srcs/users/adapter.py
  srcs/backend/srcs/users/models.py
  srcs/backend/srcs/users/serializers.py
  srcs/backend/srcs/users/urls.py
  srcs/backend/srcs/users/views.py
Labels: 🐛 Bug
